import Head from "next/head";
import styled from "styled-components";
import { useRef } from "react";
import bgimg from "../public/mountains.jpg";
import bgimg2 from "../public/styledbg.png";
import Image from "next/image";
import ImageSlider from "../components/ImageSlider";
export default function Store() {
  

 

  return (
    <div>
      <Head>
        <title>Styled HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="main-body">
        <ImageSlider></ImageSlider>
        </div>
      </main>
    </div>
  );
}

const Background = styled.div`
  //put styledbg image as div background
  background-image: url(${bgimg});
  font-size: 5rem;
`;
